---
- name: Update apt
  sudo: yes
  apt: update_cache=yes cache_valid_time=600

- name: Install System Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties

- name: ensure github.com is a known host
  lineinfile:
    dest: /home/vagrant/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"      
